firo:
    wheels_left:
      hardware_interface:
        joints:
          - left_front_wheel_joint
          - left_back_wheel_joint
    wheels_right:
      hardware_interface:
        joints:
          - right_front_wheel_joint
          - right_back_wheel_joint
    controller:
      wheels_left_state:
        type: joint_state_controller/JointStateController
        publish_rate: 25
        joints:
          - left_front_wheel_joint
          - left_back_wheel_joint
      wheels_right_state:
        type: joint_state_controller/JointStateController
        publish_rate: 25
        joints:
          - right_front_wheel_joint
          - right_back_wheel_joint
      wheels:
        type: "diff_drive_controller/DiffDriveController"
        left_wheel: 
          - 'left_front_wheel_joint'
          - 'left_back_wheel_joint'
        right_wheel: 
          - 'right_front_wheel_joint'
          - 'right_back_wheel_joint'
        publish_rate: 25
        pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        twist_covariance_diagonal: [0.2, 0.05, 0.05, 0.0, 0.0, 1.0]
        wheel_separation: 0.39955
        wheel_separation_multiplier: 2
        wheel_radius: 0.0825
        cmd_vel_timeout: 1.0
        linear:
          x:
            has_velocity_limits: true
            max_velocity: 1.0
            has_acceleration_limits: true
            max_acceleration: 4.0
        angular:
          z:
            has_velocity_limits: true
            max_velocity: 2.5028156676260793
            has_acceleration_limits: true
            max_acceleration: 10.011262670504317
        enable_odom_tf: false