plugins: 
  - {name: obstacles,        type: "costmap_2d::ObstacleLayer"} 
global_frame: odom
transform_tolerance: 0.4
update_frequency: 4
width: 4
height: 4
resolution: 0.05
always_send_full_costmap: true
obstacles:
  obstacle_range: 3
  raytrace_range: 3.5
